#!/usr/bin/env bash

set -o pipefail
set -x

source scripts/adjustEnvVars.sh || exit $?

VERSION=0.18.0
DOWNLOAD=https://bitcoincore.org/bin/bitcoin-core-${VERSION}/bitcoin-${VERSION}-${ARCH}${EXT}

#
# Download prebuild.
#
prebuild-install --debub=verbose -d $DOWNLOAD --force || exit 10

#
# Move to vendor directory.
#
rm -rf ./vendor && mkdir vendor && mv bitcoin-${VERSION}/ vendor/bitcoin || exit 20
